import icons from 'url:../../img/icons.svg'; // parcel 2; url:

export default class View {
  _data;

  /**
   * Render the received object to the DOM
   * @param {Object | Object[]} data The data to be rendered e.g. recipe
   * @param {boolean} [render=true] If false, create markup string instead of rendering to the DOM
   * @returns {undefined | string} A markup string if render=false
   * @this {Object} View instance
   * @author Antonio I.I.
   * @todo Finish implementation
   */
  render(data, render = true) {
    if (!data || (Array.isArray(data) && data.length === 0))
      return this.renderError();

    this._data = data;
    const markup = this._generateMarkup();

    if (!render) return markup;

    this._clear();
    this._parentEl.insertAdjacentHTML('afterbegin', markup);
  }

  update(data) {
    this._data = data;
    const newMarkup = this._generateMarkup(); // newMarkup is a string, generated by _generateMarkup()

    // this take the string newMarkup and convert it into a DOM object to compare it with actual one
    const newDOM = document.createRange().createContextualFragment(newMarkup);
    const newElements = Array.from(newDOM.querySelectorAll('*')); // select all the elements from the new DOM
    // Current elements
    const curElements = Array.from(this._parentEl.querySelectorAll('*')); // converting to array to compare

    newElements.forEach((newEl, i) => {
      const curEl = curElements[i]; // curElements will also loop over all elements because forEach will use index to loop on the newElements. Looping on every element of curElements

      // Updates changed text
      if (
        !newEl.isEqualNode(curEl) &&
        newEl.firstChild?.nodeValue.trim() !== ''
      ) {
        // (first) child node will contain the text, will be the text node
        // comparing the both nodes on content on false or true
        curEl.textContent = newEl.textContent; // where returns false, replace the textContent of curElements
      }

      // Updates changed attributes
      if (!newEl.isEqualNode(curEl)) {
        Array.from(newEl.attributes).forEach(
          (
            attr // we take the new elements ATTRIBUTES and loop over
          ) => curEl.setAttribute(attr.name, attr.value) // attr = new attributes; we will replace them to curEl name and value old attributes
        );
      }
    });
  }

  _clear() {
    this._parentEl.innerHTML = '';
  }

  renderSpinner() {
    const markup = `
      <div class="spinner">
        <svg>
          <use href="${icons}#icon-loader"></use>
        </svg>
      </div>
    `;
    this._clear();
    // Afterbegin-as child of parentEl
    this._parentEl.insertAdjacentHTML('afterbegin', markup);
  }

  renderError(message = this._errorMessage) {
    const markup = `
      <div class="error">
        <div>
          <svg>
            <use href="${icons}#icon-alert-triangle"></use>
          </svg>
        </div>
        <p>${message}</p>
      </div>
    `;
    this._clear();
    // Afterbegin-as child of parentEl
    this._parentEl.insertAdjacentHTML('afterbegin', markup);
  }

  renderMessage(message = this._message) {
    const markup = `
      <div class="message">
        <div>
          <svg>
            <use href="${icons}#icon-smile"></use>
          </svg>
        </div>
        <p>${message}</p>
      </div>
    `;
    this._clear();
    // Afterbegin-as child of parentEl
    this._parentEl.insertAdjacentHTML('afterbegin', markup);
  }
}
